name: pitdeck
description: "Pitdeck App"
publish_to: 'none'
version: 0.5.905








environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  mapbox_maps_flutter: ^2.5.1
  flutter_svg: ^2.0.10+1
  geolocator: ^10.0.0
  permission_handler: ^11.3.1
  rxdart: ^0.28.0
  flutter_cache_manager: ^3.4.1
  provider: ^6.1.2
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.5
  intl: ^0.20.1
  http: ^1.2.2
  socket_io_client: ^2.0.0
  redis: ^4.0.0
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.4
  image_picker: ^1.1.2
  lottie: ^3.3.1
  firebase_messaging: ^15.2.2
  firebase_core: ^3.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  
  fonts:
    - family: Orbitron
      fonts:
        - asset: fonts/Orbitron-Regular.ttf
          weight: 400
        - asset: fonts/Orbitron-Medium.ttf
          weight: 500
        - asset: fonts/Orbitron-Bold.ttf
          weight: 700
        - asset: fonts/Orbitron-Black.ttf
          weight: 900

  assets:
    - assets/map_style.json
    - assets/markers/
    - assets/images/
    - assets/card_images/
    - assets/icon/
